---
title: Assumptions and simplifications
---

As defined by [Robinson 2024](https://www.bloomsbury.com/uk/simulation-9781350445222/):

* **Assumption** - arises from incomplete knowledge - you do not know exactly how something works, so you use the best available information.
* **Simplification** - deliberate design choice - you could model something in more detail, but you opt for a simple representation.

## Assumptions

Rough notes!

* Times: Choices around cropping any times when input modelling (e.g., extreme values - 0 or very high).
* Arrivals...
    * In the model, the number of arrivals vary by day of week.
    * The arrivals are assigned a response category and a response outcome. These are assumed to not vary by day of week. We check this assumption by looking at the proportion on each day of the week of C1 v.s., C2 v.s., C3 v.s., C4 and likewise by see and convey v.s., see and treat.

## Simplifications

Rough notes!

* Grouped 'See & Convey non ED' and 'See & Convey ED' into a single 'see & convey' group.
* Queueing - simplified - priority sorting.
* They tend to take events out of the times data.
* Vehicles -
    * Only one resource per patient - not multiple.
    * Just one vehicle type - not multiple.
    * Just one fixed pool of resources - no shifts and changes in availability across week.
* Arrivals - just vary by day of week.
* Excluding hear-and-treat.
* Excluding out-of-area activity.