# Overview {.doc .doc-index}

## Core classes

Main classes used to build and run simulations.

| | |
| --- | --- |
| [SimConfig](SimConfig.qmd#ambdes.SimConfig) | Configuration for a simulation run. |
| [Logger](Logger.qmd#ambdes.Logger) | Provides log of events as the simulation runs. |
| [Model](Model.qmd#ambdes.Model) | Discrete-event simulation model for generating patient calls. |
| [Patient](Patient.qmd#ambdes.Patient) | Represents a patient who has called 999. |
| [Results](Results.qmd#ambdes.Results) | Simulation output for a single model run. |
| [Runner](Runner.qmd#ambdes.Runner) | Run the simulation for one or more replications. |

## Top-level functions

Common utility functions for calibration and configuration.

| | |
| --- | --- |
| [lognormal_sd_from_mean_p90](lognormal_sd_from_mean_p90.qmd#ambdes.lognormal_sd_from_mean_p90) | Approximate SD on the original scale for a lognormal distribution. |
| [generate_animation](generate_animation.qmd#ambdes.generate_animation) | Generate vidigi animation. |