# Runner { #ambdes.Runner }

```python
Runner(config)
```

Run the simulation for one or more replications.

## Methods

| Name | Description |
| --- | --- |
| [run_reps](#ambdes.Runner.run_reps) | Run replications, as defined by config.n_reps. |
| [run_single](#ambdes.Runner.run_single) | Run a single replication and return results. |

### run_reps { #ambdes.Runner.run_reps }

```python
Runner.run_reps()
```

Run replications, as defined by config.n_reps.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                                                                                                                                                                                  |
|--------|--------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | dict   | Dictionary with two DataFrames: - "patients": concatenated per-patient results across runs. - "run": summary of results for each run by response category. - "overall": summary of results across runs by response category. |

### run_single { #ambdes.Runner.run_single }

```python
Runner.run_single(run_number)
```

Run a single replication and return results.

#### Parameters {.doc-section .doc-section-parameters}

| Name       | Type   | Description                | Default    |
|------------|--------|----------------------------|------------|
| run_number | int    | Simulation run identifier. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                                                                                                                                                                               |
|--------|--------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | dict   | Dictionary with model instance and two DataFrames: - "model": model instance (useful for development/debugging). - "patients": per-patient results for the run. - "run": summary of results for run by response category. |