project:
  type: website

website:
  title: "Ambulance DES"
  favicon: images/pixelambulance.png
  search:
    type: textbox

  navbar:
    logo: images/pixelambulance.png
    right:
      - icon: github
        text: GitHub
        href: https://github.com/ambmodels/ambdes

  sidebar:
    - contents:
      - conceptual.qmd
      - literature.qmd
      - code.qmd
      - verification.qmd
      - validation.qmd
      - criteria.qmd
      - qa.qmd

language:
  search-text-placeholder:
    Search

format:
  html:
    theme:
      - minty
      - css/theme.scss
    css:
      - css/styles.css
    lightbox: true
    toc: true