project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Ambulance DES"
  favicon: images/pixelambulance.png
  search:
    type: textbox
  navbar:
    logo: images/pixelambulance.png
    tools:
      - icon: github
        href: https://github.com/ambmodels/ambdes
  announcement:
    dismissable: false
    content: Developed with South Western Ambulance Service NHS Foundation Trust (SWASFT). Results shown here apply only to this service. <a href="/reuse.qmd">Learn more about appropriate reuse</a>.
    position: below-navbar

metadata-files:
  - _sidebar.yml

quartodoc:
  dir: api
  out_index: index.qmd
  package: ambdes
  title: "Overview"
  sections:
    - title: "Core classes"
      desc: "Main classes used to build and run simulations."
      contents:
        - ArrivalConfig
        - SimConfig
        - Model
        - Patient
        - Results
        - Runner
  sidebar:
    file: "_sidebar.yml"
    title: "Ambulance DES"
    collapse-level: 1
    contents:
      - text: Home
        href: index.qmd
      - literature.qmd
      - modeloverview.qmd
      - section: "Quality assurance"
        contents:
          - verification.qmd
          - validation.qmd
          - criteria.qmd
          - qa.qmd
      - section: "API reference"
        contents:
          - "{{ contents }}"
      - reuse.qmd

language:
  search-text-placeholder:
    Search

format:
  html:
    theme:
      - minty
      - theme/theme.scss
    css:
      - theme/styles.css
    lightbox: true
    toc: true
    execute:
      freeze: auto
