project:
  type: website

website:
  title: "Ambulance DES"
  favicon: images/pixelambulance.png

  navbar:
    right:
      - icon: github
        text: GitHub
        href: https://github.com/ambmodels/ambdes

  sidebar:
    - contents:
      - conceptual.qmd
      - literature.qmd
      - code.qmd
      - verification.qmd
      - validation.qmd
      - qa.qmd

format:
  html:
    css:
      - css/styles.css