---
title: Code structure / infrastructure plans
---

**Python** (as ambulance team are familiar)

**SimPy** (as popular, taught on HSMA, and also should be familiar)

Environment management preferred option is **uv** as manage python version and dependencies with simple file and full lock file. Need to check whether they can use this though. Other options like conda poetry etc.

Public/private:

* Model code structured as a **package** and **public**
* Model documentation **public**
* Dummy date used in public repo for exampls
* Then will be able to import public package and run on analyses privately on own data. Public version should reproduce all key analytical steps.

Documentation in **single site** inc. project spec and code documentation via **quartodoc**

Code **object-oriented**. **Uncertainty:**

* Further thought required on how to design modular components that can be easily swapped or extended
* There will be inevitable duplicate - goal is to minimise that with a clear and maintainable structure.

Possible **input** formats include excel workbook, csv, or json

* Excel workbook proprietrary but standard
* JSON not liked in NHS model reuse interviews

Use **ruff** for linting

Use **type hints**

Write tests with **pytest** and CI/CD to run them. Arrange tests by theme, then use pytest markers for test type. Use language from our training to describe them. Have smoke test as a gate.

Have a **logging** system in place which can enable/disable. Shouldn't slow it down too much! Be wary of that

**Uncertainty** re: improvements to core structure:

* **Scenarios** - could it be improved? current way can feel a little clunky
* **Speed** - anything we could do?

Ensure address things raised in NHS model reuse interviews e.g. broad logging messages as run

Use **vidigi** for animation

Use **sim-tools** for distributions

Use **lintquarto** for the quarto book and the image alt-text linter

Once sim times get longer, use parallel processing.

**mechanism** for running all in one go from single command.

Use **conventional commits**

Use dev and main. TBC whether do dev feature main and blocking rules etc.

Numpy style docstrings

Inc. **test coverage** action

Inc. **linting** action

Documentation besides quarto:

* README and CONTRIBUTING with contents outlined in https://pythonhealthdatascience.github.io/des_rap_book/pages/guide/style_docs/documentation.html
* CHANGELOG and releases and quarto archive
* LICENSE
* CITATION.cff

Citation as per https://pythonhealthdatascience.github.io/des_rap_book/pages/guide/sharing/citation.html