---
title: Literature
bibliography: references.bib
---

<br>

This page summarises how **published ambulance DES** represent key elements of the ambulance system. It builds on the excellent review by @aboueljinane_review_2013, whose clear structure and introduction to ambulance DES have shaped how I organise the sections here. I include the DES from that review, and I have also read and added more recent ambulance DES models.

<br>

## Call arrival timing

In all DES studies, call arrivals are modeled using a **Poisson** process, so inter-arrival times are exponential. This is standard for arrival processes in healthcare DES models.

Some studies use a **Homogeneous Poisson process (HPP)** with a single arrival rate for the entire simulation period. However, most use a **Non-homogeneous Poisson process (NHPP)** where the arrival rate varies over time (e.g., by hour of day or day of week).

::: {.callout-note title="View studies" collapse="true"}

HPP:

* @silva_emergency_2010
* @van_buuren_evaluating_2012

NHPP by time of day only:

* @gigante_study_2022 - by period (00:00-08:00, 08:00-16:00, 16:00-00:00)
* @kergosien_generic_2015 - by 2-hour intervals

NHPP by time of day and day of week:

* @wei_lam_reducing_2014 - by 2-hour intervals and day of week
* @fonseca_discrete_2025 - by hour and weekday/weekend
* @aboueljinane_reducing_2012 - by hour and weekday/weekend
* @pinto_generic_2015 - by hour and day of week
* @wu_using_2009 - by hour, day of week and month

NHPP incorporating call location:

* @ingolfsson_simulation_2003 - by time of day, day of week and zone
* @maxwell_ambulance_2009 - by time of day and zone
* @berlin_mathematical_1974 - by node

Trace-driven:

* @henderson_ambulance_2005
* @uyeno_practical_1984

:::

<br>

## Call location

Models differ in how they represent where call occur:

* Some do **nothing** to represent location.
* Some embed location in the **NHPP**, giving each zone its own arrival rate.
* Some generate calls first, then **assign each call to a zone** using a probability distribution, with that distribution sometimes time-varying.

@aboueljinane_review_2013 note that studies generally assume demand is located at the **centre** of the corresponding zone (though not always).

::: {.callout-note title="View studies" collapse="true"}

Do not represent call location:

* @fonseca_discrete_2025

NHPP incorporating call location (as above): 

* @ingolfsson_simulation_2003
* @maxwell_ambulance_2009
* @berlin_mathematical_1974

Assign zones to generated calls:

* @wu_using_2009 - cluster historical calls into nodes using Nearest Neighbor Hierarchical clustering, then estimate probability a call comes from each node, and use that for a **multinomial distribution** sampling probability of each node.
* @gigante_study_2022 - calls are **evenly distributed** among the 4 regions
* @pinto_generic_2015 - city divided into cells, calls assigned using an **empirical discrete distribution** over cells that **varies by time of day and day of week**, and coordinates drawn randomly within the chosen cell.
* @kergosien_generic_2015
    * Urgent calls: assign to zone using **discrete distribution** with probability proportional to demographic weight.
    * Transfer calls: assigned to hospital (85%) or home (15%) - home coordinates drawn randomly.
* @wei_lam_reducing_2014 - call locations within each district sampled from an **empirical distribution** for each **4‑hour interval over the week**.

*Empirical is often used when data doesn't fit well to a distribution. An empirical distribution will divide the data into groups and calculate the probabilities of each.*

Unclear call location mechanism:

* @aboueljinane_reducing_2012

:::

In the studies, call location typically affects **travel times** - but can also influence resource dispatching, hospital selection and shifts.

::: {.callout-note title="View studies" collapse="true"}

From what I can spot (may have missed some):

* @wu_using_2009 - travel time, maybe hospital selection.
* @aboueljinane_reducing_2012 - travel time.
* @gigante_study_2022 - travel time to scene (not to hospital).
* @pinto_generic_2015 - dispatch, travel time, hospital selection, shifts (number of ambulances at base).
* @kergosien_generic_2015 - TODO.
* @wei_lam_reducing_2014 - TODO.

:::

<br>

## Call categories

Some studies don't include call categories.

Studies that include call categories will sample probability of each, and this can be time-varying.

::: {.callout-note title="View studies" collapse="true"}

No call category:

* @berlin_mathematical_1974 (USA)
* @maxwell_ambulance_2009 (USA)
* @silva_emergency_2010 (Brazil)
* @lee_simulation-based_2012 (Korea)

Include call category:

| Study | Country | Categories | How assigned |
| - | - | -- | - |
| @fonseca_discrete_2025 | UK | C1, C2, C3, C4 | User-supplied frequency distribution which can vary by hour of day |
| @pinto_generic_2015 | Brazil and UK | All calls receive attributes concerning nature of emergency, category of call, type of ambulance required, RRV requirement, delivery requirement, and whether dispatch will be missed. Basic life support (BLS), Advanced life support (ALS), Mental care support (MCS), Rapid response vehicle (RRV) | Empirical distribution |
| @wu_using_2009 | Taiwan | Advanced life support (ALS) or basic life support (BLS) team | Multinomial distribution |
| @gigante_study_2022 | Brazil | Basic support vehicle or advanced support vehicle | Distribution (95% basic, 5% advanced) |
| @aboueljinane_reducing_2012 | France | (1) Primary or secondary (2) Severity (0, 1, 2, 3) | Probabilities |
| @kergosien_generic_2015 | Canada | (1) Urgent or transfer (2) If urgent, transfer to hospital or not | Probabilities |
| @wei_lam_reducing_2014 | Singapore | Acuity scores | - |
| @ingolfsson_simulation_2003 | Canada |
| @henderson_ambulance_2005 | New Zealand |
| @aboueljinane_reducing_2012 | France |
| @van_buuren_evaluating_2012 | Netherlands |

:::

As described in @aboueljinane_review_2013, reasons for including include:

* Assign **hierachy** to queued calls.
* Impact **travel times**.
* Impact **activity times** (e.g., time on site, drop off time, in hospital time).
* Impact on whether **activities** happen (e.g., whether conveyed).

Output metrics may be analysed by category.

::: {.callout-note title="View studies" collapse="true"}

* @fonseca_discrete_2025 - care model (hear-and-treat, see-and-treat or see-and-convey), and ED acuity level (1 highest 5 lowest).
* @pinto_generic_2015 - whether require ambulance, whether call is non-emergency, whether call requires conveyance to hospital, whether call will cause a missing dispatch i.e., care on scene no longer necessary and ambulance makes a missing travel.
* @wu_using_2009 - on-scene time, in-hospital time.
* @gigante_study_2022 - unclear.
* @aboueljinane_reducing_2012 - order of queued calls, whether require transport to hospital, on-site time, travel time, drop-off time.
* @kergosien_generic_2015 - -
* @wei_lam_reducing_2014 - on scene treatment time.

:::

<br>

## Queue and dispatch policy

Normally nearest available vehicle.

Some incorporate call priority or possible reassignment to Cat1.

Some look for team belonging to specific area first.

Some include busy crews, if will finish their job soon.

::: {.callout-note title="View studies" collapse="true"}

**Nearest available vehicle:**

* @pinto_generic_2015
* @kergosien_generic_2015
* @berlin_mathematical_1974
* @uyeno_practical_1984
* @wears_simulation_1993
* @ingolfsson_simulation_2003
* @henderson_ambulance_2005
* @aringhieri_integrated_2010
* @maxwell_ambulance_2009
* @lee_simulation-based_2012
* @van_buuren_evaluating_2012

**Nearest available vehicle, conditioned on call priority:**

* @fonseca_discrete_2025 - Queue order by Cat1-4 priority, but if they have waited a long time, they may have their priority increased. There is also balking due to max queue size and reneging for lower priority incidents to drop out entirely or switch to ED attendance path ([source](https://nhsengland.github.io/AmbModelOpen/run/)).
* @aboueljinane_reducing_2012 - Queue order depends on call priority.
* @wu_using_2009 - Queue order depends on priority, but lower priority incidents can increase in priority if wait beyond a threshold. Some supply can be marked as holdout so a subset of ambulances is reserved for Cat1 incidents, either alwayds or triggered under certain conditions.

**Nearest base:**

* @wei_lam_reducing_2014 - If no crews available, checks next nearest base.
* @iskander_simulation_1989 - If no crews available in (or en-route to) nearest or neighbouring bases, it queues at nearest base.

**Crews/base assigned an area:** Each rescue team or base is assigned a specific area. If assigned team unavailable or all teams of assigned base are busy, then the closest available rescue team/base must take it.

* @gunes_simulation_2005 (helicopters)

**Team with smallest estimated arrival time including crews on a job** (if soon to finish and nearby, they might be smallest):

* @silva_emergency_2010

**Nearest available vehicle, but possible to reassign a rescue team serving low priority class to high priority** - @aboueljinane_reducing_2012 list two examples, neither are DES.

**Unclear:**

* @gigante_study_2022

:::

<br>

## Travel time modelling

In @aboueljinane_review_2013, they state that travel times are related to:

* Distance travelled
* Traffic conditions - rush hour, weekend v.s., weekday, day v.s., night
* Weather
* Priority of rescue
* Traffic accidents
* Quality of the roads
* Difficulty finding the exact call location.

Several different travel time models are used in the literature.

Distribution based:

a. Sample from **distribution**
b. Distribution vary by region

Or more like...:

c. **As crow flies** multiplied by speed
d. **Pre-computed shortest path** multiplied by speed
e. Divide road into **segments**, calculate travel times for each, sum

Or:

f. Any of those three, with **correction factors** for traffic, time of day, etc.

::: {.callout-note title="View studies" collapse="true"}

Several studies talk about the importance of travel time modelling...

> @henderson_ambulance_2005: "The effort we devote to this topic is justified by the great sensitivity of results to travel time assumptions, as noted both by the authors in a preliminary queueing analysis, and by a large proportion of the papers dealing with ambulance planning. For example, Carson and Batta [17] describe how the 30% savings predicted by their model turned into a 6% savings in actual tests, primarily due to the model not effectively capturing a certain travel time/distance relationship."
>
> @wei_lam_reducing_2014: "Since the performance measures are ambulance response times and utilization levels, travel time estimation forms an important consideration."

**(a) Distribution based - sample from distribution**

| Study | Times | Distribution | Varies by |
| - | - | - | - |
| @fonseca_discrete_2025 | "Time to scene" and "time to ED site" | Empirical or lognormal (lists various times using these - would need to check code to know exact) | N/A |
| @gigante_study_2022 | Time of "sending patient to hospital, release of stretcher, cleaning vehicle and returning" | Uniform | N/A |

**(b) Distribution based - distribution vary by region**

| Study | Times | Distribution | Varies by |
| - | - | - | - |
| @wu_using_2009 | Station to scene, scene to hospital, hospital to station | Unclear | Time (by call arrival time, day divided into segments) and location of activating station (ambulance usually respond within district, each district have more homogeneous traffic patterns than whole city, so calibrate based on district) |
| @gigante_study_2022 | Travel time to emergency | Triangular | If vehicle doesn't belong to region of ticket, add 5 minutes |

**(c) As crow flies multiplied by speed** (+ (f) correction factors for traffic, time of day, etc.)

* @kergosien_generic_2015
* @pinto_generic_2015 - speed differs by time (weekday/weekend), type of unit and area of city - so is corrected with a speed factor
* @silva_emergency_2010

**(d) Pre-computed shortest path multiplied by speed** (+ (f) correction factors for traffic, time of day, etc.)

* @ingolfsson_simulation_2003
* @wei_lam_reducing_2014 - Found shortest route between each origin destination pair and found ideal travel times using ArcGIS10 (based on distance and speed limit). Then calculated a correction factor for every pair based on historical ambulance travelling time. Multiple distributions of correction factors were derived by time of day, day of week, ideal travel time span, and nature of trip.
* @henderson_ambulance_2005

**(e) Divide road into segments, calculate travel times for each, sum** (+ (f) correction factors for traffic, time of day, etc.)

* @aboueljinane_reducing_2012 - Average travel time assigned to each section of road depending on type (motorway, main road, minor road, local street). For each hour of day, day of week, rescue type and priority, the travel time is calculated by diving the section length by the average speed observed in the GPS data. Travel time is sum of segments that form shortest path between origin and destination

**Unclear:**

* @uyeno_practical_1984 - unclear, but speed depends on location (rural/urban) and time of day.

:::

<br>

## Processing times

a. Include in **travel times**
b. Assume **0**
c. **Deterministic** varying by location / priority / etc.
d. Sampled from a **distribution**, can then vary by priority / day / etc.
e. **Resource** (time from ED arrival to handover emerging as ED modelled as server with given capacity and LOS)

*Note: More aggregation means less scope to explore scenarios where change specific times*

::: {.callout-note title="View studies" collapse="true"}

**(a) Include in travel times**

* @gigante_study_2022 - travel to hospital includes everything up to release of vehicle (release of stratecher, cleaning of vehicle and return)

**(b) Assume 0**

* @kergosien_generic_2015 - no wait time for calls to be answered by call handler

**(c) Deterministic varying by location/priority/etc.**

| Study | Time | Varies by |
| - | - | - |
| @maxwell_ambulance_2009 | Preparation time | Initial location of vehicles (i.e., at base or on the road) |
| @ingolfsson_simulation_2003 | On-site time | Call location, and whether transport to hospital is required |
| @ingolfsson_simulation_2003 | Drop-off time | Hospital, and call priority |
| @silva_emergency_2010 | Time betewen mterial replacements | Vehicle type |

**(d) Sampled from a distribution**, can then vary by priority/day/etc.

| Study | Time | Distribution | Varies by |
| - | - | - | - |
| @gigante_study_2022 | "Time for local care and patient preparation for travel" | Triangular | - |
| @wu_using_2009 | On-scene time and In-hospital time | Lognormal | Call type (4 types) and responder (2 skill levels) |
| @fonseca_discrete_2025 | Time from allocation to mobilise, time at scene, and time to clear | Empirical or lognormal | - |
| @aboueljinane_reducing_2012 | Regulation time, preparation time, on site time, DTR time, drop off time | Empirical | Call type (2) and priority level (4) |
| @kergosien_generic_2015 | Time at scene, discharge time at hospital, and call processing times | Gamma | - |
| @wei_lam_reducing_2014 | Empirical | Dispatch time and time on scene | Patient emergency status and conveyance status |
| @wei_lam_reducing_2014 | Empirical | Handover delay | Patient emergency status |

**(e) Resource**

* @fonseca_discrete_2025 - time from ED arrival to handover is an emerging parameter based on availability of resources... ED is modelled as a server with a given capacity and length of stay, have to queue and wait for resource.

**Unclear**

* @pinto_generic_2015 (time on scene, time at hospital, time to replenish)

:::

<br>

## Hospital selection

a. Not relevant - no choice involved (e.g., one hospital, or simple system with no individual hospital modelling)
b. Use closest hospital
c. Sample from distribution
d. Pre-determined destination by emergency type
e. Trace-driven

In @aboueljinane_review_2013, they discuss how it is common to select the closest hospital, but that @ingolfsson_simulation_2003 say 50% of patients are not transported to the closest hospital, and [Savas et al. 1969](http://doi.org/10.1287/mnsc.15.12.B608) say factors include:

* Available capacity of hospitals
* Hospital having appropriate facilities (e.g., specialists, equipment)
* Patient choice due to economic resources
* Hospital policy for selectivity

@aboueljinane_review_2013 note that hospital selection is more critical in certain scenarios like mass casualty incidents.

::: {.callout-note title="View studies" collapse="true"}

**(a) Not relevant**

* @fonseca_discrete_2025
* @gigante_study_2022
* @aboueljinane_reducing_2012 (one hospital)

**(b) Use closest hospital**

* @lee_simulation-based_2012
* @van_buuren_evaluating_2012
* @pinto_generic_2015 (closest that supplies the required care for the emergency)
* @wei_lam_reducing_2014 (except paediatric or maternity which go to a specialty hospital)

**(c) Sample from distribution**

* @ingolfsson_simulation_2003 (empirical)
* @wu_using_2009 (multinomial - unclear if stratified, but do mention that determinants include distance from scene to hospital and that other factors are also important... but doesn't appear to be stratified, think just describing context)

**(d) Pre-determined destination by emergency type**

* @silva_emergency_2010 (pre-determined schedule depending on nature and location of case, will be referred to specific centre)

**(e) Trace-driven**

* @henderson_ambulance_2005

**Unclear**

* @kergosien_generic_2015

:::

<br>

## Scenarios

Baseline: Estimated timings for given parameters

Scenarios:

* How that changes with varying **demand**
* How many **crew** (add or remove)
* How divide crew between **bases**
* **Where** bases are
* Where crew go after **release**
* **Shift** scheduling - working **hours** and **location** *E.g., optimal schedule… avoiding changes during high demand...*

Less relevant: dispatching rules (policy change), destination hospital (mass casualty)

::: {.callout-note title="View studies" collapse="true"}

**How that changes with varying demand**

**How many crew (add or remove), how divide crew between bases, and where bases are**

* @gunes_simulation_2005 - extend helicopter operation from 5 to 7 days per week
* @ingolfsson_simulation_2003 - adding new teams and bases
* @aboueljinane_reducing_2012 - adding new teams and bases
* @kergosien_generic_2015 - 150 or 200 teams, with independent or pooled fleet
* @wei_lam_reducing_2014 - changing locations
* @henderson_ambulance_2005 - vary ambulance allocations between bases
* @berlin_mathematical_1974
* @uyeno_practical_1984
* @lee_simulation-based_2012

**Where crew go after release** (@aboueljinane_review_2013 refer to this as dynamic/multi-period redeployment)

* @ingolfsson_simulation_2003 (e.g., system where don't send team to a base that already has one)
* @van_buuren_evaluating_2012 (test different strategies to keep vehicles well distributed)
* @maxwell_ambulance_2009

**Shift scheduling**

* @gigante_study_2022 - vary times (all shifts start/end at 7, 8, 9, etc.)
* @wei_lam_reducing_2014 - change start time of private ambulances (7am, 9am, 10am)
* @ingolfsson_simulation_2003 - test new schdule that avoids shift changes during high demand periods to reduce overtime

:::

<br>

## Shifts

::: {.callout-note title="View studies" collapse="true"}

* @gigante_study_2022 - Shifts are 12 hours, initially 7-7. To represent reduced resources during night shift, half the vehicles will be available.
* @pinto_generic_2015 - Resourcing levels based on schedule giving number of ambulance of each type at each base during given hour of the week
* @ingolfsson_simulation_2003 - Shift changes occur 6.30-8am, 4.30-6pm, except three units that begin 12h shift at 9am and 3pm - and also model another set of shifts too which mirror variations in call volume over time
* @kergosien_generic_2015 - Assumes teams work each day on 8h shifts. Total 150-200 teams. Assigned teams and vehicles to time slots to respect standard working constraints (e.g., maximum shift length and lunch breaks). Number of paramedic teams on duty depends on time of day.
* @wei_lam_reducing_2014 - 10 private ambulances with shifts Monday to Saturday 8am to 8pm.

:::

<br>

## Initialisation bias

::: {.callout-note title="View studies" collapse="true"}

@uyeno_practical_1984 - "starts at a time of day when congestion is very low, so no initialisation is necessary"

:::

<br>

## Run length and replications

::: {.callout-note title="View studies" collapse="true"}

TODO

:::

<br>

## Sensitivity analysis

* Demand
* Processing times
* Number of resources

::: {.callout-note title="View studies" collapse="true"}

Demand

* @fonseca_discrete_2025 change percentage see and treat and hear and treat
* @silva_emergency_2010 evaluate 10-100% increase in demand
* @iskander_simulation_1989 test 25% reduction in calls

Processing time

* @fonseca_discrete_2025 reduce time in ED
* @iskander_simulation_1989 test 50% reduction in dispatching time and 25% reduction in time on scene

Number of resources

* @fonseca_discrete_2025 increase the number of ambulances

:::

<br>

## Verification and validation

::: {.callout-note title="View studies" collapse="true"}

@aboueljinane_reducing_2012

* Similar mean response time
* Similar distribution of response times

:::