name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: main
  workflow_dispatch:


jobs:
  lint:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash -el {0}
      steps:

        - name: Check out repository
          uses: actions/checkout@v4

        - name: Install uv and Python
          uses: astral-sh/setup-uv@v7
          with:
            python-version: "3.13"
            enable-cache: true

        - name: Create uv virtualenv
          run: uv venv

        - name: Install dependencies from pyproject.toml
          run: |
            uv pip install -e .

        - name: Lint
          run: |
            uv run ruff check src tests
            uv run ruff format --check src tests
