name: lint

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
      runs-on: ubuntu-latest
      steps:

        - name: Check out repository
          uses: actions/checkout@v4

        - name: Set up Conda environment
          uses: conda-incubator/setup-miniconda@v3
          with:
            auto-activate-base: false
            activate-environment: ambdes
            environment-file: environment.yaml

        - name: Lint
          run: |
            ruff check src tests
            ruff format --check src tests
