name: Render quarto site and publish on GitHub pages
run-name: Render quarto site and publish on GitHub pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: ambdes
          environment-file: environment.yaml
          channels: conda-forge

      - name: Render site
        run: quarto render docs --execute

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
