name: tests

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      operating_systems:
        description: 'Operating systems to test on'
        type: choice
        default: 'all'
        options:
          - all
          - ubuntu-latest
          - windows-latest
          - macos-latest

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          if [[ "${{ inputs.operating_systems }}" == "all" || "${{ github.event_name }}" == "push" ]]; then
            echo 'matrix=["ubuntu-latest", "windows-latest", "macos-latest"]' >> $GITHUB_OUTPUT
          else
            echo 'matrix=["${{ inputs.operating_systems }}"]' >> $GITHUB_OUTPUT
          fi

  tests:
    permissions:
      contents: write
    needs: setup-matrix
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: ${{ fromJSON(needs.setup-matrix.outputs.matrix) }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: ambdes
          environment-file: environment.yaml
          channels: conda-forge

      - name: Run tests
        run: pytest
